<!DOCTYPE html>
<html>
<head>
</head>
<style>
body{background-color:pink;}
h2{color:blue;font-size:72;font-style:algerian;}
p{color:purple;font-size:36;font-style:bold;}
img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 40%;
}
</style>
</head>
<body>
<h2>iPHONE</h2>
<img src= "
<img src= "
alt="iphone" width= "250" height= "200">
<p>
The iPhone is a smartphone made by Apple that combines a compute$
</p>
<img src= "https://images.squarespace-cdn.com/content/v1/57053d4$
alt "iphone" width= "250" height= "200">
<p>
iPhones are faster. ...
Better hardware and software integration. ...
Easiest phone to use. ...
alt="iphone" width= "250" height= "200">
<p>
The iPhone is a smartphone made by Apple that combines a computer, iPod, digital camera and cellular phone into one device with a touchscreen interface. The iPhone runs the iOS operating system (OS), and as of 2017, there were 2.2 million apps available for it through the Apple App Store, according to Statista.
</p>
<img src= "https://images.squarespace-cdn.com/content/v1/57053d4c01dbae40ae9ccb39/1553123872188-090BWNXM2CPB0ZO5EG2A/ke17ZwdGBToddI8pDm48kBsbwg_wUHZ4gbzA0cRCrG9Zw-zPPgdn4jUwVcJE1ZvWQUxwkmyExglNqGp0IvTJZamWLI2zvYWH8K3-s_4yszcp2ryTI0HqTOaaUohrI8PI_dhXWvv3hLaH670uJpSBKHIhUa4ZSYzDDLAHyw1DDSAKMshLAGzx4R3EDFOm1kBS/iphonexfrontback-800x573.jpg?format=500w
alt "iphone" width= "250" height= "200">
<p>
iPhones are faster. ...
Better hardware and software integration. ...
Easiest phone to use. ...
OS updates when you want them. ...
The best apps first. ...
No bloatware! ...
</p>
</body>
</html>Easiest phone to use. ...
OS updates when you want them. ...
The best apps first. ...
No bloatware! ...
</p>
</body>
</html>Easiest phone to use. ...
OS updates when you want them. ...
The best apps first. ...
No bloatware! ...
Easiest phone to use. ...
OS updates when you want them. ...
The best apps first. ...
No bloatware! ...
</p>
</body>
</html>
